// app/lib/auto-pr.ts

import { OpenAI } from "openai";

const client = new OpenAI({
  baseURL: "https://models.inference.ai.azure.com",
  apiKey: process.env.AZURE_OPENAI_KEY,
});

export async function createAutoFixPR(
  owner: string,
  repo: string,
  issueNumber: number,
  filePath: string,
  detectiveReport: any,
) {
  const token = process.env.GITHUB_PAT;
  if (!token) throw new Error("Missing GITHUB_PAT");

  console.log(`\n🤖 [Agent 4] The Coder is waking up to fix: ${filePath}`);

  // Get the current file content from GitHub
  const fileUrl = `https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`;
  const fileRes = await fetch(fileUrl, { headers: { Authorization: `Bearer ${token}` } });
  const fileData = await fileRes.json();

  if (!fileData.content) throw new Error("Could not find file on GitHub.");

  const currentContent = Buffer.from(fileData.content, "base64").toString("utf-8");
  const fileSha = fileData.sha;

  // The Coder Agent writes the fix
  const coderPrompt = `
    You are an expert developer. You are fixing a bug in this file: ${filePath}.
    The Detective Agent found this root cause: ${detectiveReport.root_cause}
    
    CRITICAL: Output ONLY the fully corrected raw code for this file. 
    Do not use markdown blocks (\`\`\`typescript). Do not add explanations. Just the raw code text.
  `;

  const fixResponse = await client.chat.completions.create({
    model: "gpt-4o",
    messages: [
      { role: "system", content: coderPrompt },
      { role: "user", content: currentContent },
    ],
  });

  const fixedContent = fixResponse.choices[0].message?.content?.trim() || currentContent;

  // Create a new branch in GitHub
  const branchName = `ai-fix-issue-${issueNumber}-${Date.now()}`;
  const baseBranchRes = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/git/ref/heads/main`,
    {
      headers: { Authorization: `Bearer ${token}` },
    },
  );
  const baseBranchData = await baseBranchRes.json();
  const baseSha = baseBranchData.object.sha;

  await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs`, {
    method: "POST",
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: baseSha }),
  });

  // Commit the fixed file to the new branch
  await fetch(fileUrl, {
    method: "PUT",
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      message: `🤖 Auto-fix for Issue #${issueNumber}`,
      content: Buffer.from(fixedContent).toString("base64"),
      sha: fileSha,
      branch: branchName,
    }),
  });

  // Open the Pull Request
  const prRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
    method: "POST",
    headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
    body: JSON.stringify({
      title: `🤖 Auto-Fix: Resolves Issue #${issueNumber}`,
      body: `This PR was autonomously generated by SyncSphere Agent 4 (The Coder).\n\n**Detective Root Cause:** ${detectiveReport.root_cause}\nCloses #${issueNumber}`,
      head: branchName,
      base: "main",
    }),
  });

  const prData = await prRes.json();
  console.log(`✅ [Agent 4] PR CREATED SUCCESSFULLY: ${prData.html_url}`);
  return prData.html_url;
}
